### ISSUE TITLE
Task 3: Upload images

### ISSUE THREAD

**Issue by jordipainan** [UB-ES-2018/picturest#1]
Test

**Comment by JoseManuelVasquez** [comment]
He implementado las peticiones POST y GET para las imágenes, aún queda pendiente de acabarlo, alguien puede echarme una mano para integrar el usuario con la imagen?

**Comment by jordipainan** [comment]
Yo mismo, esta tarde me pondré!

**Comment by jordipainan** [comment]
Done! :)
